const map_list = {
    The_Room : [
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwEe iwwwwwwwwwwww",
                    "wwwwwwwwwww wwwwwwwwwwww",
                    "wwwwwwwwwwwpwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww"
                    ],
    Enemies : [
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwEe iwwwwwwwwwwww",
                    "wwwwwwwwwww wwwwwwwwwwww",
                    "wwwwwwwwwwwpwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww"
                    ],
    The_Exit : [
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwEe iwwwwwwwwwwww",
                    "wwwwwwwwwww wwwwwwwwwwww",
                    "wwwwwwwwwwwpwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww"
                    ],
    North_America : [
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwEe iwwwwwwwwwwww",
                        "wwwwwwwwwww wwwwwwwwwwww",
                        "wwwwwwwwwwwpwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww"
                        ],
    Australia : [
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwEe iwwwwwwwwwwww",
                    "wwwwwwwwwww wwwwwwwwwwww",
                    "wwwwwwwwwwwpwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww"
                    ],
    Africa : [
                "wwwwwwwwwwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwwwwwwwwwww",
                "wwwwwwwwEe iwwwwwwwwwwww",
                "wwwwwwwwwww wwwwwwwwwwww",
                "wwwwwwwwwwwpwwwwwwwwwwww",
                "wwwwwwwwwwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwwwwwwwwwww"
                ],
    Asia : [
                "wwwwwwwwwwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwwwwwwwwwww",
                "wwwwwwwwEe iwwwwwwwwwwww",
                "wwwwwwwwwwwewwwwwwwwwwww",
                "wwwwwwwwwwwpwwwwwwwwwwww",
                "wwwwwwwwwwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwwwwwwwwwww"
                ],
    South_America : [
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwewwwwwwwwwwww",
                        "wwwwwwwwwww wwwwwwwwwwww",
                        "wwwwwwwwEe iwwwwwwwwwwww",
                        "wwwwwwwwwww wwwwwwwwwwww",
                        "wwwwwwwwwwwpwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww"
                        ],
    Familiar_Scene : [
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwEe iwwwwwwwwwwww",
                        "wwwwwwwwwww wwwwwwwwwwww",
                        "wwwwwwwwwwwpwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww"
                        ],

    //requirements to get badges silver and up (bronze is completion)
    //silver
    The_Room_silver : 3,
    Enemies_silver : 4,
    The_Exit_silver : 5,
    North_America_silver : 7,
    Australia_silver : 7,
    Africa_silver : 7,
    Asia_silver : 7,
    South_America_silver : 7, 
    Familiar_Scene_silver : 7,

    //gold
    The_Room_gold : 2,
    Enemies_gold : 3,
    The_Exit_gold : 4,
    North_America_gold : 5,
    Australia_gold : 5,
    Africa_gold : 5,
    Asia_gold : 5,
    South_America_gold : 5, 
    Familiar_Scene_gold : 5,

    //plat
    plat : 1
};

window.map_list = map_list;