const map_list = {
    The_Room : [
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwEe iwwwwwwwwwwww",
                    "wwwwwwwwwww wwwwwwwwwwww",
                    "wwwwwwwwwwwpwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww"
                    ],
    Enemies : [
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwEe iwwwwwwwwwwww",
                    "wwwwwwwwwww wwwwwwwwwwww",
                    "wwwwwwwwwwwpwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww"
                    ],
    The_Exit : [
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwEe iwwwwwwwwwwww",
                    "wwwwwwwwwww wwwwwwwwwwww",
                    "wwwwwwwwwwwpwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww"
                    ],
    North_America : [
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwEe iwwwwwwwwwwww",
                        "wwwwwwwwwww wwwwwwwwwwww",
                        "wwwwwwwwwwwpwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww"
                        ],
    Australia : [
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwEe iwwwwwwwwwwww",
                    "wwwwwwwwwww wwwwwwwwwwww",
                    "wwwwwwwwwwwpwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww"
                    ],
    Africa : [
                "wwwwwwwwwwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwwwwwwwwwww",
                "wwwwwwwwEe iwwwwwwwwwwww",
                "wwwwwwwwwww wwwwwwwwwwww",
                "wwwwwwwwwwwpwwwwwwwwwwww",
                "wwwwwwwwwwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwwwwwwwwwww"
                ],
    Asia : [
                "wwwwwwwwwwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwwwwwwwwwww",
                "wwwwwwwwEe iwwwwwwwwwwww",
                "wwwwwwwwwwwewwwwwwwwwwww",
                "wwwwwwwwwwwpwwwwwwwwwwww",
                "wwwwwwwwwwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwwwwwwwwwww",
                "wwwwwwwwwwwwwwwwwwwwwwww"
                ],
    South_America : [
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwewwwwwwwwwwww",
                        "wwwwwwwwwww wwwwwwwwwwww",
                        "wwwwwwwwEe iwwwwwwwwwwww",
                        "wwwwwwwwwww wwwwwwwwwwww",
                        "wwwwwwwwwwwpwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww"
                        ],
    Familiar_Scene : [
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwEe iwwwwwwwwwwww",
                        "wwwwwwwwwww wwwwwwwwwwww",
                        "wwwwwwwwwwwpwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww"
                        ],
};

window.map_list = map_list;