const map_list = {
    The_Room : [
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwww      wwwwwwwwww",
                    "wwwwwwww wwww wwwwwwwwww",
                    "wwwww       w wwwwwwwwww",
                    "wwwww ww ww w wwwwwwwwww",
                    "wwwww ww wwpw wwwwwwwwww",
                    "wwwww ww wwww wwwwwwwwww",
                    "wwwww ww wE   wwwwwwwwww",
                    "wwwwwwww wwwwwwwwwwwwwww",
                    "wwwwwwww ww wwwwwwwwwwww",
                    "wwwwwwww    wwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww"
                    ],
    Enemies : [
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwpwwwwwwwwwwww",
                    "wwwwwwwww     e wwwwwwww",
                    "wwwwwwwww w www      www",
                    "wwwwwwwww wewww wwww www",
                    "wwwwwwwww w wwwwwwww www",
                    "wwwwwwwww w   wEwe   www",
                    "wwwwwwwww wwwww wwwwwwww",
                    "wwwwwwwww       wwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwww"
                    ],
    The_Exit : [
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "w            e  wwwwwwww",
                    "w wwwwwww w www wwwwwwww",
                    "w wwwwwww wwwww      www",
                    "w wwwww    wwww wwww www",
                    "w  www  ww ww   wwww www",
                    "ww www www ww wwwwwwwwww",
                    "ww www  p     w   e  w w",
                    "ww wwwwwww wwww wwww w w",
                    "wwe    www  www wwww w w",
                    "ww www wwww www wwww w w",
                    "ww www    w     wwww w w",
                    "ww  ww ww w wwwwwwww   w",
                    "www wwewwwwwwwwwwwwwww w",
                    "www ww     E           w",
                    "wwwwwwwwwwwwwwwwwwwwwwww"
                    ],
    North_America : [
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "wE       e            ww",
                    "wwwwwwwwwwwwwwwwwwwww ww",
                    "w   wwww   e    wwwww ww",
                    "w w   ww wwwwww w     ww",
                    "w wwwwww    www wwwww  w",
                    "w     wwwww ww      ww w",
                    "wwwww wwwww ww wwww ww w",
                    "w     ww   eww wwww ww w",
                    "w wwweww ww  e      ww w",
                    "w www    ww www www ww w",
                    "w www wwwww www www ww w",
                    "w          w      w ww w",
                    "w wwwwwww wwwwwww w ww w",
                    "w     wp               w",
                    "wwwwwwwwwwwwwwwwwwwwwwww"
                    ],
    Australia : [
                "wwwwwwwwwwwwwwwwwwwwwwww",
                "wp        e          Eww",
                "wwww w wwwwwwwwwww w www",
                "w    w w       e  w w  w",
                "w wwwww w wwwwwwwww w ww",
                "w w     w   e       w  w",
                "w w wwwww wwwwwwwwwww ww",
                "w w w         w       ww",
                "w   w wwwwwww w wwwww ww",
                "www w w       w     w ww",
                "w   w w wwwwwww www w  w",
                "w www w w  e    w w w ww",
                "w       w wwwwwww w   ew",
                "wwwwwwww w       www www",
                "w   e    w wwwww       w",
                "wwwwwwwwwwwwwwwwwwwwwwww"
                ],
    Africa : [
            "wwwwwwwwwwwwwwwwwwwwwwww",
            "wp       e             w",
            "w wwwwwwwwww wwwwwwwww w",
            "w wwwwww   e    wwwwww w",
            "w     ww wwwwww wwwwww w",
            "wwwww ww    www www ww w",
            "wwwww ww ww wwwww   wwww",
            "wwwww ww ww www   w    w",
            "w        wwewww www ww w",
            "w wwwew www  e  www ww w",
            "w www w wwwwwww www ww w",
            "w wwwww wwwwwww wwwwww w",
            "w        w          ww w",
            "w wwwwwwwww wwwwwww ww w",
            "w     wwwww www      E w",
            "wwwwwwwwwwwwwwwwwwwwwwww"
            ],
    Asia : [
            "wwwwwwwwwwwwwwwwwwwwwwww",
            "w      w E            ww",
            "w wwwwwwwwwwwwwwwwwww ww",
            "w wwwwww   e          ww",
            "w e   ww wwwwww wwwww  w",
            "wwwww ww    wwwwwwwwwwww",
            "w     ww wwwww         w",
            "www wwww w   ww wwwwww w",
            "w   ww   wwewww www e  w",
            "www ww wwwww e  www ww w",
            "www w e   ww wwwwww ww w",
            "www www wwww wwwwww ww w",
            "w   e   w           ww w",
            "w wwwwwwwwwwwwwwwww ww w",
            "w p                    w",
            "wwwwwwwwwwwwwwwwwwwwwwww"
            ],
    South_America : [
                    "wwwwwwwwwwwwwwwwwwwwwwww",
                    "w        e         wE ww",
                    "w wwwwwwwwwwwwwwwwwww ww",
                    "w wwwwww   e    wwwww ww",
                    "w     wwwwwwwww wwwww ww",
                    "wwwww ww    www www w  w",
                    "wwwww    ww www     ww w",
                    "wwwwwwww ww www www ww w",
                    "w     ww wwewww www ww w",
                    "w wwweww ww  e  www ww w",
                    "w www ww ww www www ww w",
                    "w www ww ww www www ww w",
                    "w     p             ww w",
                    "w wwwwwwwww wwwwwww ww w",
                    "w    ewwwww www        w",
                    "wwwwwwwwwwwwwwwwwwwwwwww"
                    ],
    Familiar_Scene : [
                        "wwwwwwwwwwwwwwwwwwwwwwww",
                        "wwwwwwwwwwwpwwwwwwwwwwww",
                        "wwwwwwwwwww wwwwwwwwwwww",
                        "wwwwwwwwwww wwwwwwwwwwww",
                        "wwwwwwwwwww wwwwwwwwwwww",
                        "wwwwwwwwwww wwwwwwwwwwww",
                        "wwwwwwwwwww wwwwwwwwwwww",
                        "wwwwwwwwwww wwwwwwwwwwww",
                        "wwwwwwwwwww wwwwwwwwwwww",
                        "wwwwwwwwwww wwwwwwwwwwww",
                        "wwwwwwwwwww wwwwwwwwwwww",
                        "wwwwwwwwwww wwwwwwwwwwww",
                        "wwwwwwwwwww wwwwwwwwwwww",
                        "wwwwwwwwwww wwwwwwwwwwww",
                        "wwwwwwwwwwwEwwwwwwwwwwww",
                        "wwwwwwwwwwwwwwwwwwwwwwww"
                        ],

    //requirements to get badges silver and up (bronze is completion)
    //silver
    The_Room_silver : 3,
    Enemies_silver : 4,
    The_Exit_silver : 5,
    North_America_silver : 7,
    Australia_silver : 7,
    Africa_silver : 7,
    Asia_silver : 7,
    South_America_silver : 7, 
    Familiar_Scene_silver : 7,

    //gold
    The_Room_gold : 2,
    Enemies_gold : 3,
    The_Exit_gold : 4,
    North_America_gold : 5,
    Australia_gold : 5,
    Africa_gold : 5,
    Asia_gold : 5,
    South_America_gold : 5, 
    Familiar_Scene_gold : 5,

    //plat
    plat : 1
};

//set session storage only if map_list dosent exist
if (!sessionStorage.getItem("map_list")) {
    sessionStorage.setItem("map_list", JSON.stringify(map_list));
}
